Python for Data Analysis page 140

In [1]:
!pip install numpy

In [3]:
import numpy as np

- 2D array = row x column
- 3D array = depth/block x row x column

In [4]:
np.random.randn(2,3)

array([[ 0.19929242,  1.28285351, -1.14651669],
       [-0.3635868 , -0.28254911, -1.76766971]])

In [17]:
data1 = [[5,6,7,8],[1,2,3,4]]
data1 = np.array(data1)
data2 = [[1,2,3,4],[5,6,7,8]]
data2 = np.array(data2)

In [9]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [10]:
np.zeros((3,6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [11]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [12]:
np.arange(15).dtype

dtype('int32')

In [13]:
np.zeros(10).dtype

dtype('float64')

In [19]:
data2 * data2

array([[ 1,  4,  9, 16],
       [25, 36, 49, 64]])

In [20]:
data1 + data2

array([[ 6,  8, 10, 12],
       [ 6,  8, 10, 12]])

In [21]:
arr = np.arange(10)
arr[5:8]

array([5, 6, 7])

In [24]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [33]:
arr2d = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr2d[2]) # Index two
print(arr2d[0][2]) # Index at zero, with element of index two
print(arr2d[0,2]) # Equivalent to above

[7 8 9]
3
3


In [34]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])
print(arr3d[0]) #2x3 array
print(arr3d[1, 0]) #index at one, whole element at index zero
print(arr3d[1, 0, 1])
print(arr3d[1][0][1])


[[1 2 3]
 [4 5 6]]
[7 8 9]
8
8


In [38]:
print(arr[1:6])
print(arr[:2])
print(arr2d[1, :2])
print(arr2d[:2, 1:])

[ 1  2  3  4 12]
[0 1]
[4 5]
[[2 3]
 [5 6]]


In [40]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7,4)

In [41]:
data

array([[-0.17716494,  0.58352008, -1.32432445, -1.66717124],
       [-0.08266056, -0.00537532, -0.60624364, -1.96694756],
       [ 1.51102714, -0.00486854,  0.06880653,  1.20656519],
       [ 0.59803559,  0.20456665, -0.89333346, -0.80075351],
       [ 0.71296122,  0.15025596, -1.73524062, -0.89464407],
       [ 0.40969224,  2.96650442, -1.0592762 ,  0.55796337],
       [-0.67344635,  0.73331058,  1.12000125, -0.37190839]])

In [42]:
names == 'Bob'

array([ True, False, False,  True, False, False, False])

In [43]:
data[names == 'Bob']

array([[-0.17716494,  0.58352008, -1.32432445, -1.66717124],
       [ 0.59803559,  0.20456665, -0.89333346, -0.80075351]])