# Task 5 - Hazim Fitri Bin Ahmad Faudzi - P152419

##### Create two arrays each of sizes: single 1d array, 3x3, 2x4, 4x2 and 5x5. Hence, you will have 10 arrays all together and these arrays must be generated via random number. Name your arrays in order from A to J.  

Import Library

In [2]:
import numpy as np

Generate 2 1d array, 2 3x3 array, 2 2x4 array, 2 4x2 array, 2 5x5 array

In [32]:
A = np.random.rand(1)
B = np.random.rand(5)
C = np.random.rand(3, 3)
D = np.random.rand(3, 3)
E = np.random.rand(2, 4)
F = np.random.rand(2, 4)
G = np.random.rand(4, 2)
H = np.random.rand(4, 2)
I = np.random.rand(5, 5)
J = np.random.rand(5, 5)

##### Using numpy library: perform at least twenty (20) functions from Table 4-3, Table 4-4, Table 4-5 and Table 4-7 from Python for Data Analysis book.

##### You must:  
1. Perform operation on single array  
2. Perform operation on two arrays of same size (eg. multiplication, etc.)  
3. Perform operation on two arrays of different size (eg. dot product between array of size 2x4 and 4x2)

Note: you must include all arrays created.

Table 4-3 Unary ufuncs (page 169)

In [33]:
# Operation on single array
print(np.abs(A))
print('----------------------------------------------')
print(np.sqrt(B))
print('----------------------------------------------')
print(np.exp(C))
print('----------------------------------------------')
print(np.rint(D))
print('----------------------------------------------')
print(np.isnan(E))
print('----------------------------------------------')
print(np.cos(F))
print('----------------------------------------------')
print(np.log(G))
print('----------------------------------------------')
print(np.ceil(H))
print('----------------------------------------------')
print(np.floor(I))
print('----------------------------------------------')
print(np.logical_not(J))
print('----------------------------------------------')

[0.54226612]
----------------------------------------------
[0.67266282 0.52957211 0.93688001 0.99356725 0.92620755]
----------------------------------------------
[[1.18046466 1.29766905 2.20286695]
 [1.57527231 1.95078283 2.29432429]
 [2.18374162 1.31392286 2.09378585]]
----------------------------------------------
[[1. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]]
----------------------------------------------
[[False False False False]
 [False False False False]]
----------------------------------------------
[[0.73363523 0.82308032 0.98874578 0.99093842]
 [0.97938695 0.97089001 0.77667516 0.9923783 ]]
----------------------------------------------
[[-4.20979104 -0.59988027]
 [-0.44799862 -0.74983734]
 [-1.09920841 -0.04195012]
 [-2.02792952 -1.25489804]]
----------------------------------------------
[[1. 1.]
 [1. 1.]
 [1. 1.]
 [1. 1.]]
----------------------------------------------
[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
---------------------

Table 4-4 Binary universal functions (page 170)

In [34]:
# Operation on two  same size arrays
print(np.divide(C, D))
print('----------------------------------------------')
print(np.power(J, I))
print('----------------------------------------------')
print(np.maximum(J, J))
print('----------------------------------------------')
print(np.divide(I, I))
print('----------------------------------------------')
print(np.copysign(D, C))
print('----------------------------------------------')
print(np.greater(C, C))

[[0.2133117  0.87037111 0.85347152]
 [0.73147061 1.42093058 1.75518573]
 [2.53017756 0.33837642 2.93859946]]
----------------------------------------------
[[0.74055885 0.98972608 0.9878779  0.98821849 0.94810681]
 [0.53821896 0.96567039 0.82830876 0.98065233 0.93073059]
 [0.85347527 0.62370183 0.9987605  0.37262809 0.81370763]
 [0.25141059 0.87539249 0.4484259  0.97052281 0.65849859]
 [0.71831686 0.95214553 0.8159135  0.79128441 0.44897681]]
----------------------------------------------
[[0.65278685 0.91389281 0.70651469 0.8041914  0.82667658]
 [0.43732941 0.39999419 0.32172158 0.77726839 0.87684809]
 [0.33695317 0.53494182 0.95514557 0.35263245 0.78065706]
 [0.12914641 0.86111855 0.06370479 0.96829948 0.06545767]
 [0.53204719 0.89694095 0.45003028 0.78839477 0.28808069]]
----------------------------------------------
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
----------------------------------------------
[[0.7777733  0.2993776  0.9253

Table 4-5 Basic array statistical methods (page 176)

In [35]:
# Operation on single array
print(np.sum(A))
print('----------------------------------------------')
print(np.mean(B))
print('----------------------------------------------')
print(np.cumprod(C))
print('----------------------------------------------')
print(np.std(D))
print('----------------------------------------------')
print(np.min(E))
print('----------------------------------------------')
print(np.argmin(F))
print('----------------------------------------------')
print(np.cumsum(G))
print('----------------------------------------------')
print(np.max(H))
print('----------------------------------------------')
print(np.argmax(I))
print('----------------------------------------------')
print(np.var(J))

0.5422661245152643
----------------------------------------------
0.6911404678373638
----------------------------------------------
[0.16590814 0.04323062 0.0341418  0.015515   0.0103676  0.00860965
 0.00672448 0.0018359  0.00135668]
----------------------------------------------
0.23242970465545268
----------------------------------------------
0.041955774564725656
----------------------------------------------
7
----------------------------------------------
[0.01484947 0.56372682 1.20263238 1.67507578 2.00821047 2.96712808
 3.09873581 3.38384073]
----------------------------------------------
0.9694738651541535
----------------------------------------------
23
----------------------------------------------
0.07979678496479094


Table 4-7 Commonly used numpy.linalg functions (page 184)

In [51]:
# Operation on single array
print(np.diag(J))
print('----------------------------------------------')
print(np.trace(C))
print('#############################################')

# Operation on two  same size arrays
print(np.dot(C, D))
print('#############################################')

# Operation on two different size arrays
np.dot(F, G)

[0.65278685 0.39999419 0.95514557 0.96829948 0.28808069]
----------------------------------------------
1.5731127257616138
#############################################
[[0.53470919 0.80942242 0.47540945]
 [1.02493006 1.12033383 0.94549932]
 [1.00519817 0.95845659 1.03773953]]
#############################################


array([[0.4647398 , 0.87784633],
       [0.40082292, 0.91456509]])